id: A1B949843
title: A Prayer of Aspiration for the Copper-Coloured Mountain of Glory
type: translation
pechas:
- I14360220
- I2F8DAA3D
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:47:49.045577
  last_modified_at: 2023-01-04 11:47:49.045581
  collections:
  - Dudjom Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I14360220/EC56: AEE0
  I2F8DAA3D/3884: AEE0
